name: Build and Push Retail App Images

on:
  push:
    branches:
      - main

env:
  REGISTRY: docker.io
  DB_IMAGE: retail-db
  BACKEND_IMAGE: retail-backend
  FRONTEND_IMAGE: retail-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    # ---------------- DB ----------------
    - name: Build & Push DB Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.DB_IMAGE }}:latest ./db
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.DB_IMAGE }}:latest

    # ---------------- BACKEND ----------------
    - name: Build & Push Backend Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.BACKEND_IMAGE }}:latest ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.BACKEND_IMAGE }}:latest

    # ---------------- FRONTEND ----------------
    - name: Build & Push Frontend Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.FRONTEND_IMAGE }}:latest ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.FRONTEND_IMAGE }}:latest
